sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # config gcloud-sdk
  # - bash ./scripts/config-gcd.sh
before_script:
  # Log in to the docker CLI
  - bash ./scripts/login-dockerhub.sh $DOCKER_PASSWORD $DOCKER_NAME
script:
  # Build docker images
  - bash ./scripts/build-docker-img.sh $DOCKER_NAME $SHA
  # Take hose images and push them to docker hub
  - bash ./scripts/push-img-to-dockerhub.sh $DOCKER_NAME $SHA
deploy:
  - provider: script
    script: bash scripts/deploy-to-gke.sh $DOCKER_NAME $SHA
    on:
      branch: master
notifications:
  email: false
